# Generated by Django 4.2.4 on 2023-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_ozon_wb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
